chore(zj): if user does not choose new session, exit

diff --git a/dot_zsh_utils b/dot_zsh_utils
--- a/dot_zsh_utils
+++ b/dot_zsh_utils
@@ -1,3 +1,32 @@
+
+# Opens a fzf menu to attach to an existing Zellij session
+# If none exists, will just create a new one
+zj() {
+  if ! type fzf &> /dev/null; then
+    echo "fzf not found, installing..."
+    brew install fzf
+  fi
+
+  local session
+    session=$(
+    {
+        echo "New session" 
+        zellij list-sessions --no-formatting | awk '{print $1}'
+    } | fzf --exit-0 --no-sort --prompt="Select session > "
+    )
+
+  if [[ "$session" == "New session" ]]; then
+    zellij
+  elif [[ -n "$session" ]]; then
+    zellij attach "$session"
+  else
+    :
+  fi
+}
+
+
+
+
 # View largest disk usage
 alias largest='du -h 2> /dev/null | sort -hr | head -n20'
 
